// Code generated by mockery v2.20.0. DO NOT EDIT.

package account

import mock "github.com/stretchr/testify/mock"

// MockAccountUsecaseInterface is an autogenerated mock type for the AccountUsecaseInterface type
type MockAccountUsecaseInterface struct {
	mock.Mock
}

type MockAccountUsecaseInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountUsecaseInterface) EXPECT() *MockAccountUsecaseInterface_Expecter {
	return &MockAccountUsecaseInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: account
func (_m *MockAccountUsecaseInterface) Create(account *Actors) error {
	ret := _m.Called(account)

	var r0 error
	if rf, ok := ret.Get(0).(func(*Actors) error); ok {
		r0 = rf(account)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccountUsecaseInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAccountUsecaseInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - account *Actors
func (_e *MockAccountUsecaseInterface_Expecter) Create(account interface{}) *MockAccountUsecaseInterface_Create_Call {
	return &MockAccountUsecaseInterface_Create_Call{Call: _e.mock.On("Create", account)}
}

func (_c *MockAccountUsecaseInterface_Create_Call) Run(run func(account *Actors)) *MockAccountUsecaseInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*Actors))
	})
	return _c
}

func (_c *MockAccountUsecaseInterface_Create_Call) Return(_a0 error) *MockAccountUsecaseInterface_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccountUsecaseInterface_Create_Call) RunAndReturn(run func(*Actors) error) *MockAccountUsecaseInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// getByUsername provides a mock function with given fields: username
func (_m *MockAccountUsecaseInterface) getByUsername(username string) (Actors, error) {
	ret := _m.Called(username)

	var r0 Actors
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (Actors, error)); ok {
		return rf(username)
	}
	if rf, ok := ret.Get(0).(func(string) Actors); ok {
		r0 = rf(username)
	} else {
		r0 = ret.Get(0).(Actors)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountUsecaseInterface_getByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getByUsername'
type MockAccountUsecaseInterface_getByUsername_Call struct {
	*mock.Call
}

// getByUsername is a helper method to define mock.On call
//   - username string
func (_e *MockAccountUsecaseInterface_Expecter) getByUsername(username interface{}) *MockAccountUsecaseInterface_getByUsername_Call {
	return &MockAccountUsecaseInterface_getByUsername_Call{Call: _e.mock.On("getByUsername", username)}
}

func (_c *MockAccountUsecaseInterface_getByUsername_Call) Run(run func(username string)) *MockAccountUsecaseInterface_getByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockAccountUsecaseInterface_getByUsername_Call) Return(_a0 Actors, _a1 error) *MockAccountUsecaseInterface_getByUsername_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountUsecaseInterface_getByUsername_Call) RunAndReturn(run func(string) (Actors, error)) *MockAccountUsecaseInterface_getByUsername_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockAccountUsecaseInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockAccountUsecaseInterface creates a new instance of MockAccountUsecaseInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockAccountUsecaseInterface(t mockConstructorTestingTNewMockAccountUsecaseInterface) *MockAccountUsecaseInterface {
	mock := &MockAccountUsecaseInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
